export const loginFields = [
  {
    id: 'emailField',
    name: 'email',
    type: 'email',
    label: 'Correo electronico',
    placeholder: 'Usuario',
    icon: '/image/user-icon.png',
    tabIndex: 1,
    autoComplete: 'email',
  },
  {
    id: 'passwordField',
    name: 'password',
    type: 'password',
    placeholder: 'Contraseña',
    label: 'Contraseña',
    icon: '/image/eye-open-icon.png',
    tabIndex: 2,
    activeForgot: true,
  },
  {
    id: 'dniField',
    name: 'dni',
    type: 'text',
    label: 'DNI',
    placeholder: 'DNI',
    icon: '/image/dni-icon.png',
    tabindex: 3,
    autoComplete: 'dni',
  },
];
