export const loginFields = [
  {
    id: 'emailField',
    name: 'email',
    type: 'email',
    label: 'Correo electronico',
    placeholder: 'Usuario',
    icon: '/image/user-icon.png',
    tabIndex: 1,
    autoComplete: 'email',
  },
  {
    id: 'passwordField',
    name: 'password',
    type: 'password',
    placeholder: 'Contraseña',
    label: 'Contraseña',
    icon: '/image/eye-open-icon.png',
    tabIndex: 2,
    activeForgot: true,
  },
];

export const registerFields = [
  {
    id: 'dniField',
    name: 'dni',
    type: 'text',
    label: 'DNI',
    placeholder: 'DNI',
    icon: '/image/dni-icon.png',
    tabindex: 1,
    autoComplete: 'dni',
  },
  {
    id: 'firstName',
    name: 'firstName',
    type: 'text',
    label: 'Nombre',
    placeholder: 'Nombre',
    icon: '/image/dni-icon.png',
    tabIndex: 2,
    autoComplete: 'firstName',
  },
  {
    id: 'lastName',
    name: 'lastName',
    type: 'text',
    label: 'Apellido',
    placeholder: 'Apellido',
    icon: '/image/dni-icon.png',
    tabIndex: 3,
    autoComplete: 'firstName',
  },
  {
    id: 'emailField',
    name: 'email',
    type: 'email',
    label: 'Correo electronico',
    placeholder: 'Email',
    icon: '/image/user-icon.png',
    tabIndex: 4,
    autoComplete: 'email',
  },
  {
    id: 'passwordField',
    name: 'password',
    type: 'password',
    placeholder: 'Contraseña',
    label: 'Contraseña',
    icon: '/image/eye-open-icon.png',
    tabIndex: 5,
    activeForgot: true,
  },
];
