# Generated by Django 5.1.2 on 2025-02-02 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OnboardingQuestionnaire',
            new_name='Onboarding',
        ),
    ]
